### ISSUE TITLE
Still in development?

### ISSUE THREAD

**Issue by johnwargo** [arduino-libraries/ArduinoCloud#8]
I've been playing around with the Cloud offering and haven't been able to make it work. It looks like this library hasn't been updated in a while and there's pretty much no documentation on the board I'm using (MKR WIFI 1010) or the Cloud offering. Need some help with the docs?  I'm happy to help.

**Comment by cmaglie** [comment]
This library has been superseded by

- https://github.com/arduino-libraries/ArduinoIoTCloud
- https://github.com/arduino-libraries/ArduinoCloudThing

and many other, a lot of development effort has been put into them. Please check the Arduino blog, more news are coming soon.
